server:
  port: 8090

spring:
  datasource:
    name: alimysql
    #url: jdbc:mysql://47.108.168.114:3306/sys?useUnicode=true&characterEncoding=UTF8
    url: jdbc:mysql://47.108.168.114:3306/sys
    username: root
    password: 71291949e470


